### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by Zsolt-R** [appticles/wordpress-progressive-web-apps#7]
Fatal error: require_once(): Failed opening required .../wp-content/plugins/progressive-web-apps/inc/class-pwapp-options.php in .. \wp-content\plugins\wordpress-progressive-web-apps-master\core\class-pwapp.php on line 4

**Comment by abarbulescu** [comment]
If you download the plugin directly from Github and not the WordPress Plugins repository you need to rename the plugin directory from 'wordpress-progressive-web-apps-master' to 'progressive-web-apps' since the Github repository has a different name and also appends the branch name.

**Comment by Zsolt-R** [comment]
Forgot about this,works now thanks!
